### ISSUE TITLE
Module broken?

### ISSUE THREAD

**Issue by janl** [hoodiehq/grunt-release-hoodie#9]
Installed the latest version and got:

```
getting Error: Cannot find module 'inquirer'
   ...
   at Object.<anonymous> (/Users/jan/Work/hoodie/hoodie-plugin-send-email/node_modules/grunt-release-hoodie/bin/setup.js:6:16)

```

I added `inquirer` manually, but then got:

```
now Error: Cannot find module '../tasks/util/setup'
```

Giving up for now.

**Comment by svnlto** [comment]
clear npm cache?

**Comment by janl** [comment]
at least three times

**Comment by boennemann** [comment]
`rm -rf node_modules && npm install` doesn't work either? :(

**Comment by janl** [comment]
Empty project, full log:

```
> cd /tmp
/tmp 
> mkdir test
mkdir: test: File exists
/tmp 
> cd 
/tmp 
> mkdir foo
/tmp 
> cd foo
/tmp/foo 
> npm cache clear
/tmp/foo 
> npm install grunt-release-hoodie
npm WARN deprecated grunt-semantic-release@0.2.1: The standalone "semantic-release" version is now available. Use it instead.
npm WARN excluding symbolic link query -> vendors/jquery/src/
npm WARN excluding symbolic link query -> vendors/jquery/src/
|
> intern@2.2.2 install /private/tmp/foo/node_modules/grunt-release-hoodie/node_modules/hoodie-integration-test/node_modules/intern
> node support/fixdeps.js

grunt-release-hoodie@2.9.1 node_modules/grunt-release-hoodie
├── extend@1.3.0
├── ncp@0.6.0
├── shelljs@0.3.0
├── animals@0.0.3 (unique-random@0.1.1, minimist@0.2.0)
├── superb@1.1.3 (unique-random-array@1.0.0, meow@3.0.0)
├── grunt-subgrunt@0.4.4 (async@0.9.0, glob@4.4.0)
├── grunt@0.4.5 (which@1.0.8, dateformat@1.0.2-1.2.3, eventemitter2@0.4.14, getobject@0.1.0, rimraf@2.2.8, colors@0.6.2, async@0.1.22, grunt-legacy-util@0.2.0, hooker@0.2.3, exit@0.1.2, nopt@1.0.10, minimatch@0.2.14, glob@3.1.21, lodash@0.9.2, coffee-script@1.3.3, underscore.string@2.2.1, iconv-lite@0.2.11, findup-sync@0.1.3, grunt-legacy-log@0.1.1, js-yaml@2.0.5)
├── grunt-shell@0.7.0 (chalk@0.4.0)
├── grunt-semantic-release@0.2.1 (semver-regex@0.1.1, async@0.9.0, npm-which@1.0.2, github@0.2.3, conventional-changelog@0.0.11, grunt-conventional-changelog@1.1.0, grunt@0.4.5, grunt-bump@0.0.15, js-yaml@3.2.7, inquirer@0.5.1)
└── hoodie-integration-test@1.0.4 (grunt-hoodie@0.5.4, glob@4.4.0, chai@2.0.0, chai-as-promised@4.2.0, load-grunt-tasks@0.6.0, grunt@0.4.5, intern@2.2.2, hoodie-cli@0.6.3)
/tmp/foo 
> ./node_modules/.bin/setup 

module.js:340
    throw err;
          ^
Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/private/tmp/foo/node_modules/grunt-release-hoodie/bin/setup.js:6:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
/tmp/foo 
```
```
> node -v
v0.10.36
> npm --version
2.5.1
```

**Comment by boennemann** [comment]
Can reproduce, will look into this.
